### ISSUE TITLE
No Ruuvitags detected

### ISSUE THREAD

**Issue by barcar** [Scrin/ruuvi-go-gateway#4]
I have this running in docker on a Raspberry PI 4 using the sample docker compose file. I have 6 Ruuvitags nearby (all of which are detectable using the native Ruuvi iPhone app).

When I turn on trace level debug I can see lots of BLE advertisements but none are detected as being for the Ruuvitags. For example:

`[2022-7-12 08:46:55] [trace] [/go/src/github.com/Scrin/ruuvi-go-gateway/gateway/gateway.go] Received data from BLE adapter, is_ruuvi: false, data: 4C0003161100000277C0A856200000000000000000000000000B, mac: 0D:72:48:9F:69:10, rssi: -59`

`[2022-7-12 08:46:55] [trace] [/go/src/github.com/Scrin/ruuvi-go-gateway/gateway/gateway.go] Received data from BLE adapter, is_ruuvi: false, data: 4C0002152686F39CBADA4658854AA62E7E5E8B8D000100000B, mac: 05:3E:AB:3B:0D:ED, rssi: -61`

`[2022-7-12 08:46:55] [trace] [/go/src/github.com/Scrin/ruuvi-go-gateway/gateway/gateway.go] Received data from BLE adapter, is_ruuvi: false, data: A705051001000000000000022200CA, mac: F3:33:A1:94:48:35, rssi: -66
`

So, I assume the BLE stack is working ok. If I change all_advertisements to true, I can see MQTT posts for the detected devices. So MQTT is working too. My tags are using data format 5 and running recent firmware.

Have you any idea why the gateway would see everything EXCEPT my Ruuvitags?

**Comment by Scrin** [comment]
Since you get some data that looks like it's real, BLE stack should be working correctly indeed. You mentioned iPhone, there is (or was? not sure) some limitations in some cases with at least some firmware versions that in some cases using the Ruuvi Station iPhone app will stay connected to the tag(s), which will prevent the tags from broadcasting the measurements during that. Here is one forum thread which stumbled up on this "feature" (near the end of the thread): https://f.ruuvi.com/t/sync-issues-with-ios/4613/17 - perhaps that could be related? Which firmware version specifically do you have on the tags?

I don't own any iPhones (or other iOS/Apple devices) so I can't test this myself unfortunately, but I suspect the issue is that the tags are not actually broadcasting. To double-check that, keep the `all_advertisements` enabled and see if you get any kind of data from the ruuvitags (check the MAC addresses). Basically when the `all_advertisements` is true, ruuvi-go-gateway will "blindly" forward *all* broadcast data it gets from ble, no matter if the data makes sense in any way so the ruuvitags should show up there if they're actually *broadcasting* anything.

**Comment by barcar** [comment]
Thanks - that's helpful. I force-quit the Ruuvi app on my phone and restarted everything but still no tags are being logged in the GW.

I fired up the nRF Connect app on my phone and it can see multiple Ruuvi tags advertising (without connecting). Regarding firmware version - it looks like they are on v3.31.1+default (I didn't check them all).

![IMG_3473](https://user-images.githubusercontent.com/2155858/178489706-404e4233-4dde-4576-ad60-d95d069de41f.PNG)

**Comment by Scrin** [comment]
Interesting. That looks correct, the tags are broadcasting in the correct format, with the correct company identifier, so nothing wrong with the tags either. Next suspicion is the BLE stack, it might be possible that some other service is filtering the BLE data somehow on your raspberry pi.

If you compare the devices seen by nRF Connect and what ruuvi-go-gateway sees on your pi, is it just the ruuvitags missing or are there other "missing" devices?

You could also check if there are any other services or apps active on your raspberry that use bluetooth which could interfere

**Comment by barcar** [comment]
I’ll dig into that. Thanks again.

is this relevant? [https://f.ruuvi.com/t/home-assistant-ruuvitags-not-properly-working-after-fw-upgrade/5562/3](url)

> v2->v3 update adds a scan response to Bluetooth data, my guess is that your BLE scanner requests that scan response and doesn’t know how to handle it.
>
>This issue has been fixed in most community projects, updating software versions to latest might work. If not, the fix is most likely to either use passive BLE scanning which does not request scan response or to add support for discarding the scan response / other unknown data from RuuviTag

Like the OP there I also recently upgraded firmware from v2 to v3.

**Comment by Scrin** [comment]
Shouldn't be, since ruuvi-go-gateway uses passive scanning already so that doesn't apply.

I just verified this by grabbing a fresh ruuvitag with v3.30 firmware (I use a custom firmware on my "normal tags") and tested running ruuvi-go-gateway on a raspberry pi and the data seems to flow normally

**Comment by barcar** [comment]
This is the strangest thing. I build a fresh Raspberry Pi and even using hcitool, I can't see the tags. I guess it's not a gateway issue then! Thanks again for your help.

**Comment by Scrin** [comment]
No problem. If/when you find out the cause, I'd be happy to hear about it :)
