### ISSUE TITLE
Rate Limit

### ISSUE THREAD

**Issue by barcar** [Scrin/ruuvi-go-gateway#6]
Would it be possible to add a configuration to set a rate limit for tag readings?

Maybe something like "only send readings if they are x seconds older than the last reading" (for any sensor/metric).

**Comment by Scrin** [comment]
Something like that would likely be possible, although the exact way to do that would require behavioral changes. Currently ruuvi-go-gateway "mimics" the physical gateway behavior, which is:

- For MQTT, the measurements are published as they are received in real time over the open connection to a MQTT server
- For HTTP, the ruuvi-go-gateway "ticks" at 10s interval (by default, but this is configurable) and sends the newest received measurement for each tag

To add a rate limit, I suppose the MQTT implementation could either throttle by discarding or buffering measurements, and the HTTP version could perhaps be changed to skip a "tick" if no new measurements were received since the previous HTTP POST.

Could you elaborate a little why you need a rate limit, so that I can come up with the best solution?

**Comment by barcar** [comment]
Really it’s just about the frequency of readings being pumped into Influx DB. The default Ruuvitag frequency is much higher than I need.

I could rate limit it downstream but I was wondering if it could be done at (almost) source in the gateway.

I’m using MQTT, so discarding intermediate readings would work for me.

**Comment by Scrin** [comment]
Right, I guess adding an optional rate limit to MQTT specifically could be done with reasonable effort, and it would also be useful in situations where the MQTT server is either rate limited itself or a service that's billed by the amount of messages or something, so I think it would be an useful feature to have

I need to think about the optimal way to do this along with a few other architectural changes I have planned, since right now the benefit of MQTT is that it's a "fire-and-forget" system that supports virtually unlimited amount of sensors without any memory or CPU overhead, but adding a rate limiter would increase the CPU and memory usage since it would need to keep track of each sensor separately to "remember" when they were last transmitted

That combined with the fact that my free time is pretty limited at the moment means that it will take some time before I get to implement this

**Comment by hulkk** [comment]
Any updates regarding this?

I'm also using ruuvi-go-gateway with ruuvibridge to forward measurements to InfluxDB Cloud and in my use case one measurement per 5 minutes is enough. Now the data will be sent every few seconds. 

For the mean time I think I will use Telegraf & two MQTT topics to limit the amount of data sent to InfluxDB.

**Comment by Scrin** [comment]
I think I will actually implement this as a feature in RuuviBridge rather than ruuvi-go-gateway, as it would be more appropriate there. That way ruuvi-go-gateway will remain as close as possible to the physical gateway, while RuuviBridge would then do all the extra stuff. I'll try to get that done this weekend

**Comment by Scrin** [comment]
I.. apparently had forgotten that this already exists as a feature on RuuviBridge. See the `minimum_interval` [configuration option](https://github.com/Scrin/RuuviBridge/blob/master/config.sample.yml) for RuuviBrdige under the publisher config (`influxdb_publisher` or `mqtt_publisher`). This feature was added in RuuviBrdige v0.1.3 a while ago.
